language: cpp
dist: trusty
sudo: required
os:
  - linux
  - osx
branches:
  only:
  - ci_mar17
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-6
    - g++-6
    - libfreetype6-dev
    - libfontconfig1-dev
    - python

#before_script:
#  - if [ $TRAVIS_OS_NAME == linux ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test && sudo apt-get update -qq && sudo apt-get install -y libfreetype6-dev libfontconfig1-dev python gcc-6 g++-6; fi
script:
  - if [ $TRAVIS_OS_NAME == linux ]; then CC=/usr/bin/gcc-6 CXX=/usr/bin/g++-6 python build_scripts/indigo-release-libs.py; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then python build_scripts/indigo-release-libs.py; fi
  - python build_scripts/indigo-make-by-libs.py --type=python
#after_success:
#  - if [ $TRAVIS_OS_NAME == linux ]; then export INDIGO_ZIP_SUFFIX=linux; fi
#  - if [ $TRAVIS_OS_NAME == osx ]; then export INDIGO_ZIP_SUFFIX=mac; fi
#  - export INDIGO_PYTHON_SHA1_SUM=`shasum -a 1 dist/indigo-python-*-$INDIGO_ZIP_SUFFIX.zip | awk '{print $1}'`
#  - curl -H "X-JFrog-Art-Api:$INDIGO_ARTIFACTORY_API_KEY" -H "X-Checksum-Sha1:$INDIGO_PYTHON_SHA1_SUM" -X PUT "https://artifactory.epam.com/artifactory/EPM-LSOP/indigo/releases/latest/indigo-python-latest-$ZIP_SUFFIX.zip" -T dist/indigo-python-*-$INDIGO_ZIP_SUFFIX.zip
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/$INDIGO_GITTER_KEY
    on_success: change
    on_failure: always
    on_start: never
