[tool.poetry]
name = "bingo_elastic"
version = '1.5.1'
description = "Bingo API for using with Elasticsearch"
authors = ["EPAM Systems Life Science Department"]

[tool.poetry.dependencies]
python = "^3.7"
elasticsearch = "7.15.1"
"epam.indigo" = "^1.5.1"

[tool.poetry.dev-dependencies]
pytest = "^4.6"
mypy = "^0.790"
pylint = "^2.6.0"
black = "^20.8b1"
pre-commit = "^2.9.3"
wheel = "^0.36.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 79
