[build-system]
requires = [
    "setuptools>=40.9.0",
    "wheel"
]
build_backend = "setuptools.build_meta"

[tool.black]
line-length = 79

[tool.isort]
profile = "black"
line_length = 79

[tool.flake8]
max-line-length = 79
extend-ignore = "E203, E501"
